apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-model-app
  labels:
    app: iris-model-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-model-app
  template:
    metadata:
      labels:
        app: iris-model-app
    spec:
      serviceAccountName: iris-model
      containers:
      - name: iris-model-app
        image: artemgalliamov/iris-model-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"